import type { Metadata } from "next";
import { Saira } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";

const saira = Saira({
  subsets: ["latin"], 
  weight: ["400", "500", "600", "700"], 
  variable: "--font-saira", 
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
     className={saira.variable}
      >
        <Header />
        <main>{children}</main>
      </body>
    </html>
  );
}
